traceRepos:
  - org/repo1
  - org/repo2
  - benjamin-747/r2cn-bot-test

taskMaintainers:
  - benjamin-747

noneProjectComment: >
  Thanks for joining R2CN Projetc! You need to first submit a PR to modify the .github/config.yaml file to apply for your project to be included in the R2CN program.

noneAdminComment: >
  You do not have permission to apply for the R2CN internship tasks. Please contact your organization administrator to submit a PR and modify the .github/config.yaml file.
